version: "3"

networks:
  my-network:
    driver: bridge
volumes:
  dir-site:
    driver_opts:
      device: ./
      type: bind
      o: bind
services:
  my-php:
    container_name: php-product
    build:
      dockerfile: Dockerfile
      context: ./php/
    hostname: php
    restart: always
    networks:
      - my-network
    volumes:
      - dir-site:/home/sites/
  my-httpd:
    container_name: c-httpd01
    image: "httpd:latest"
    hostname: httpd
    restart: always
    networks:
      - my-network
    volumes:
      - dir-site:/home/sites/
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "9999:80"
      - "443:443"
  my-mysql:
    container_name: mysql-product
    image: "mysql:latest"
    networks:
      - my-network
    volumes:
      - ./db:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD:123abc
      - MYSQL_DATABASE=db_site
      - MYSQL_USER=siteuser
      - MYSQL_PASSWORD=sitepass